services:
  proxy: 
    image: hamptonmoore/umasssmp_proxy
    build:
      dockerfile: ./proxy.Dockerfile
    ports:
      - 3000:3000
      - 25565:25565
    depends_on:
      - redis
  redis:
    image: redis